apiVersion: v1
kind: Service
metadata:
  name: hello-world-clusterip
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
    - name: metrics
      port: 8080
      targetPort: 8000
  selector:
    app: example
