---
apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
    - name: main
      image: sikalabs/nginx-public
      ports:
        - containerPort: 80
      env:
        - name: MY_DEFAULT_TOKEN
          value: default
        - name: MY_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: MY_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: token
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: config
      volumeMounts:
        - name: secret
          mountPath: /usr/share/nginx/html/password.txt
          subPath: password
        - name: secret
          mountPath: /usr/share/nginx/html/tokenFromString.txt
          subPath: tokenFromString
        - name: config
          mountPath: /usr/share/nginx/html/config.txt
          subPath: config
        - name: config
          mountPath: /usr/share/nginx/html/hello.html
          subPath: hello.html
        - name: config
          mountPath: /usr/share/nginx/html/configmap
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
  volumes:
    - name: config
      configMap:
        name: my-config
    - name: secret
      secret:
        secretName: my-secret
