apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen2
spec:
  selector:
    matchLabels:
      app: bluegreen2
  replicas: 10
  template:
    metadata:
      labels:
        app: bluegreen2
    spec:
      containers:
        - name: hello-world
          image: sikalabs/hello-world-server:green
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
