apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-mount-example
spec:
  selector:
    matchLabels:
      app: pvc-mount-example
  replicas: 3
  template:
    metadata:
      labels:
        app: pvc-mount-example
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
            limits:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginx-data
---
apiVersion: v1
kind: Service
metadata:
  name: pvc-mount-example
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pvc-mount-example
