auth:
  username: admin
  password: admin
replicaCount: 3
ingress:
  enabled: true
  path: /
  hostname: rabbitmq.k8s.sikademo.com
  # TLS
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
