apiVersion: v1
kind: ResourceQuota
metadata:
  name: limits
spec:
  hard:
    requests.cpu: 300m
    requests.memory: 400Mi
    limits.cpu: 300m
    limits.memory: 400Mi

    services.loadbalancers: "0"

    count/deployments.apps: "3"
    count/pods: "10"
